name: CI Checks

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    name: "Check formatting"
    steps:
      - uses: actions/checkout@v5
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Run rustfmt
        run: cargo fmt --check

  unit-tests:
    runs-on: ubuntu-latest
    name: "Unit Tests"
    steps:
      - name: Install protoc
        run: |
          PB_REL="https://github.com/protocolbuffers/protobuf/releases"
          curl -LO $PB_REL/download/v30.2/protoc-30.2-linux-x86_64.zip
          unzip protoc-30.2-linux-x86_64.zip -d $HOME/.local
          export PATH="$PATH:$HOME/.local/bin"
      - uses: actions/checkout@v5
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Run unit tests
        run: cargo test --lib --verbose

  doc-tests:
    runs-on: ubuntu-latest
    name: "Doc Tests"
    steps:
      - name: Install protoc
        run: |
          PB_REL="https://github.com/protocolbuffers/protobuf/releases"
          curl -LO $PB_REL/download/v30.2/protoc-30.2-linux-x86_64.zip
          unzip protoc-30.2-linux-x86_64.zip -d $HOME/.local
          export PATH="$PATH:$HOME/.local/bin"
      - uses: actions/checkout@v5
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Run doc tests
        run: cargo test --doc --verbose

  feature-tests:
    runs-on: ubuntu-latest
    name: "Unit and Doc Tests (all features)"
    steps:
      - name: Install protoc
        run: |
          PB_REL="https://github.com/protocolbuffers/protobuf/releases"
          curl -LO $PB_REL/download/v30.2/protoc-30.2-linux-x86_64.zip
          unzip protoc-30.2-linux-x86_64.zip -d $HOME/.local
          export PATH="$PATH:$HOME/.local/bin"
      - uses: actions/checkout@v5
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Run unit tests
        run: cargo test --lib --all-features --verbose
      - name: Run doc tests
        run: cargo test --doc --all-features --verbose

  integration-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        hatchet_version:
          - v0.68.0
          - v0.69.0
          - v0.70.0
          - v0.71.0
          - v0.72.0
          - v0.73.0
          - v0.74.0
          - v0.75.0
          # no v0.76.0 as it was never released (v0.76 only had -alpha.* releases)
          - v0.77.0
          - v0.78.0
          - v0.79.0
          - v0.80.0
          - v0.81.0
          - v0.82.0
          - v0.83.0
          - latest
    env:
      TEST_HATCHET_LITE_VERSION: ${{ matrix.hatchet_version }}
    name: "Integration Tests - Hatchet Version: ${{ matrix.hatchet_version }}"
    steps:
      - name: Install protoc
        run: |
          PB_REL="https://github.com/protocolbuffers/protobuf/releases"
          curl -LO $PB_REL/download/v30.2/protoc-30.2-linux-x86_64.zip
          unzip protoc-30.2-linux-x86_64.zip -d $HOME/.local
          export PATH="$PATH:$HOME/.local/bin"
      - uses: actions/checkout@v5
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Run integration tests
        run: cargo test --test integration_tests --all-features --verbose
